"""removes household_id from user

Revision ID: 559326d03e21
Revises: b7b490827ff1
Create Date: 2023-02-13 20:01:34.444056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559326d03e21'
down_revision = 'b7b490827ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_household_id_fkey', type_='foreignkey')
        batch_op.drop_column('household_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('household_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_household_id_fkey', 'household', ['household_id'], ['id'])

    # ### end Alembic commands ###
