"""changes what info user model collects

Revision ID: ef9882e3ba73
Revises: 09a9ebb84617
Create Date: 2023-02-13 09:58:43.406885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9882e3ba73'
down_revision = '09a9ebb84617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_hoh', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_head_of_household')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('phoneNumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_head_of_household', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_hoh')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
